baseURL = 'https://erny.dev/'
languageCode = 'en-us'
title = 'Erny'
theme = "hugo-theme-console"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
    name = "articles/"
    url = "articles/"
  [[params.navlinks]]
    name = "posts/"
    url = "posts/"
  [[params.navlinks]]
    name = "tools/"
    url = "tools/"
  [[params.navlinks]]
    name = "github/"
    url = "https://github.com/ErnyTech"
  [[params.navlinks]]
    name = "telegram/"
    url = "https://t.me/ErnyT"
